- name: Install base dependencies
  become: true
  apt:
    update_cache: true
    cache_valid_time: 86400
    name:
    - python3-dev
    - gfortran
    - mpi-default-bin
    - mpi-default-dev
    - ssh
    - xz-utils

- name: "Install nwchem data for Ubuntu {{ ansible_distribution_release|lower }}"
  become: true
  apt:
    deb: "{{ nwchem_deb_url_data }}"
  register: nwchem_install_data
  # retry in case of bad connection
  retries: 2
  until: not nwchem_install_data.failed
  delay: 10


- name: "Install nwchem main for Ubuntu {{ ansible_distribution_release|lower }}"
  become: true
  apt:
    deb: "{{ nwchem_deb_url_main }}"
  register: nwchem_install_main
  # retry in case of bad connection
  retries: 2
  until: not nwchem_install_main.failed
  delay: 10

- name: Add release notes (version)
  include_role:
    name: release_notes
  vars:
    section: "nwchem"
    option: "version"
    value: "{{ nwchem_version }}"
  when: release_notes is defined and release_notes

- name: Add release notes (usage)
  include_role:
    name: release_notes
  vars:
    section: "nwchem"
    option: "usage"
    value: >-
      nwchem is compiled and installed in /usr/bin.
      Simply run 'nwchem'.
  when: release_notes is defined and release_notes

- name: Run tests
  when: run_tests and (nwchem_install_data.changed or nwchem_install_main.changed)
  include_tasks: tests.yml
  loop:
  - "h20.nw"
